export default {
    // Simple routes
    home: '/',
    aboutUs: '/o-nas',
    offer: '/oferta',
    trainers: '/trenerzy',
    localizations: '/lokalizacje',
    groupWorkouts: '/treningi-grupowe',
    multiWorkouts: '/treningi-3x3',
    individualTrainings: '/treningi-indywidulane',
    applicationForm: '/formularz-zgloszeniowy',
    frequentlyAskedQuestions: '/najcześciej-zadawane-pytania',
    resignations: '/rezygnacje',
    leagueRecruitment: '/nabory-ligowe',
    sportsCamps: '/obozy-sportowe',
    recreationalDayCamps: '/polkolonie-rekreacyjne',
    membershipDeclaration: '/deklaracja-czlonkowska',
    clubRegulations: '/regulamin-klubu',
    individualTrainingContract: '/umowa-treningi-indywidualne',
    participantCard: '/karta-uczestnika-oboz-polkolinia',
    photos: '/zdjecia',
    movies: '/filmy',
    sponsorship: '/sponsoring',
    openingOfANewLocation: '/otwarcie-nowej-lokalizacji',
    pyraPoznan: '/pyra-poznan',
    simpleHelp: '/prosta-pomoc',
};
